## android.toml -*- mode: toml -*-
doot-version = "0.13"

[[locations]]
pdf_source                 = "{data_drive}/library/pdfs"
push_pdfs                  = "{pdf_source}"
data_drive                 = "/media/john/data"
android_root               = "remote::>/storage/6331-3162"

[[tasks.android]]
name                 = "device.find"
version              = "0.1"                # <str>
ctor                 = "task"               # <type>
doc                  = ["Run Find On the Device, write the results locally"] # <list[str]>
android_root         = "/storage/6331-3162"
setup = [
    { do="dootle.android.actions:AndroidRunning"} ,
]
actions = [
    { do="dootle.android.actions:AndroidRemoteCmd", cmd="find", args=["{android_root!p}/Library/pdf_library", "-type", "f"] },
    { do="write!", from_="adb_result", to="{temp!p}/adb_files" }
]


[[tasks.android]]
name                       = "push.pdfs"
version                    = "0.1"
ctor                       = "job"
doc                        = ["Push pdfs to device"]
accept_fn                  = "taskscode.android:select_dirs"
roots                      = ["{push_pdfs!p}"]
actions     = [
    {do="job.walk",   update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={insert=['fpath'], now=["android_root!p"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks", key_="fpath"},
    {do="job.queue",  from_="tasks"},
]
sub_actions = [
    { do="log", msg="Pushing: {fname} to {android_root!p}/Library/pdf_library/{fname}"},
    { do="dootle.android.actions:AndroidRunning" },
    { do="dootle.android.actions:AndroidPush", local="{fpath!p}", remote="{android_root!p}/Library/pdf_library/" },
]
