# #  rust-toolchain.toml -*- mode: TOML -*-
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel     = "1.88"
components  = ["rustfmt", "clippy"]
targets     = []
