#!/usr/bin/env python3
"""
Release script for bumping, tagging, and building changelog

Call as: cargo do-release {level}

"""
# Imports:

# ##-- stdlib imports
import datetime
import enum
import functools as ftz
import itertools as itz
import logging as logmod
import pathlib as pl
import re
import time
import collections
import contextlib
import hashlib
from copy import deepcopy
from uuid import UUID, uuid1
from weakref import ref
import atexit # for @atexit.register
import faulthandler
# ##-- end stdlib imports

import sys
import sh

# ##-- types
# isort: off
# General
import abc
import collections.abc
import typing
import types
from typing import cast, assert_type, assert_never
from typing import Generic, NewType, Never, Final
from typing import no_type_check, final, override, overload
# Protocols and Interfaces:
from typing import Protocol, runtime_checkable
# isort: on
# ##-- end types

# ##-- type checking
# isort: off
if typing.TYPE_CHECKING:
    from typing import Final, ClassVar, Any, Self
    from typing import Literal, LiteralString
    from typing import TypeGuard
    from collections.abc import Iterable, Iterator, Callable, Generator
    from collections.abc import Sequence, Mapping, MutableMapping, Hashable

    from jgdv import Maybe
## isort: on
# ##-- end type checking

##-- logging
logging = logmod.getLogger(__name__)
##-- end logging

# Vars:
LEVELS : Final[tuple[str, ...]] = ("major", "minor", "patch")
try:
    git         = sh.git
    towncrier   = sh.towncrier
    version     = sh.version

except sh.CommandNotFound as err:
    print(err)
    sys.exit(1)

# Body:

def check_repo():
    failed = False
    match git("--no-pager", "diff").strip():
        case "":
            pass
        case _:
            print("There are unstaged changes, commit or stash them before releasing.")
            failed = True

    try:
        towncrier("check")
    except sh.ErrorReturnCode_1:
        print("There are no change fragments, add at least one.")
        failed = True

    if failed:
        sys.exit(-1)

def bump_version(level:str) -> tuple[str, str]:
    print(f"Bumping {level} of Project")
    current_version = version("version").strip()
    version(level, "set", "+")
    new_version = version("version").strip()
    assert(current_version != new_version)
    return current_version, new_version

def generate_changelog() -> None:
    print("Generating changelog updates")
    towncrier("build", "--yes")

def finalize_repo(new_version:str) -> None:
    print("Committing Changelog and Version")
    git("add", "--all")
    git("commit", "-m", f"[Release]: {new_version}")
    print(f"Tagging Version: {new_version}")
    git("tag", new_version)

def main():
    """
    Generalised release process
    """
    bump_level   : str
    new_version  : str
    ##--|

    match sys.argv:
        case [*_, "check"]:
            check_repo()
            sys.exit(0)
        case [*_, str() as bump_level] if bump_level in LEVELS:
            check_repo()
            current_version, new_version = bump_version(bump_level)
            assert(bool(new_version))
            print(f"{current_version} -> {new_version}")
            generate_changelog()
            finalize_repo(new_version)
            sys.exit(0)
        case _:
            print("No Bump Level Provided")
            sys.exit(-1)

##-- ifmain
if __name__ == "__main__":
    main()
##-- end ifmain
