# -*- mode:conf-toml; -*-
[settings.general]
notify                   = { say-on-exit = false }
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true, print_levels={action="WARN", execute="WARN" } }
max_steps                = 100_000

[settings.tasks]
sources = ["doot/global", "doot/repo_chores"] # Files or directories where task specs can be loaded from, expanded according to [[locations]] keys
code    = []                        # Directories where task specific code can be imported from, expanded according to [[locations]] keys
sleep   = { task=0.2, subtask=1, batch=1 }

[settings.commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = []}

[plugins]
# Allows for defining shorthands
command        = { tasks = "doot.cmds.list_cmd:ListCmd" }

[logging]
stream  = { level="WARNING", filter=[],                 target="stdout", format="{levelname:<8} : {message}"  }
file    = { level="DEBUG",   filter=["chainguard"],      target="rotate", format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filename_fmt="doot.log" }
printer = { level="NOTSET", colour=true,                target=["stdout", "rotate"], format="{message}", filename_fmt="doot_printed.log" }

[logging.subprinters]
default       = {level="WARNING"}
shutdown      = {level="WARNING",    format="Shutdown: {message}", target="stdout"}
cmd           = {level="INFO"}
task          = {level="INFO" }
header        = {level="INFO" }
task_header   = {level="INFO"}

[logging.extra]

[[locations]]
temp            = {path=".temp", cleanable=true}
templates       = "."
logs            = "{temp}/logs"
build           = "{temp}/build"
docs            = "docs"
data            = "data"
image_blacklist = {path="{temp}/image.blacklist", file=true}
