# -*- mode:conf-toml; -*-
[settings.general]
notify                   = { say-on-exit = false }
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing = true, print_levels={action="WARN", execute="WARN" } }
max_steps                = 100_000

[settings.tasks]
sources = ["doot/global", "doot/repo_chores"] # Files or directories where task specs can be loaded from, expanded according to [[locations]] keys
code    = []                        # Directories where task specific code can be imported from, expanded according to [[locations]] keys
sleep   = { task=0.2, subtask=1, batch=1 }


[logging]
stream  = { level="WARNING", format="{levelname:<8} : {message}", filters=["doot"], target="stdout" }
file    = { level="DEBUG",   format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filters=["doot"], target="file" }
printer = { level="INFO",    format="{message}", colour=true, target="stdout", filter=[] }

[logging.subprinters]
# Divider subprinters: artifact, task_header, header
task_header  = {format="---{message}", colour=true, target="stdout"}

# # Process subprinters: cmd, setup, shutdown, track, task_loop
# cmd          = {level="INFO",    format="{message}"}
setup        = {level="INFO",    format="-- Setup: {message}"}
shutdown     = {level="WARNING", format="-- Shutdown: {message}"}
track        = {level="WARNING", format="-- Tracking: {message}"}
report       = {level="INFO",    format="{message}", target="stdout", colour=true}

# Event Subprinters: success, fail, skip, sleep, header, help, queue, report, task_state
## action_exec, action_group, task
task         = {}
task_state   = {level="WARNING", format="Task State: {message}"}
success      = {level="WARNING", format="-- Success {message}"}
fail         = {level="WARNING", target="stdout", format="!!!! {message}"}
queue        = {format="++++ {message}"}
action_group = {level="WARNING", format="Action Group: {message}"}
action_exec  = {level="WARNING", format="--------> Action Execution: {message}", target="stdout", colour=true}
[logging.extra]
"doot._printer.checkloc" = {level="WARNING"}

[plugins]
# Allows for defining shorthands
command        = { other-run = "doot.cmds.run_cmd:RunCmd", tasks = "doot.cmds.list_cmd:ListCmd" }
report-line    = {}
reporter       = {}
action         = {}
task           = {}

[commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = []}

[[locations]]
temp            = {loc=".temp", cleanable=true}
logs            = "{temp}/logs"
build           = "{temp}/build"
docs            = "docs"
data            = "data"
image_blacklist = "{temp}/image.blacklist"
