# -*- mode:conf-toml; -*-
[startup]
doot_version         = "1.1"
loaders              = { commands="default", task="default", parser="default" }
sources              = {tasks=["doot/global", "doot/repo_chores"], code=[]}
skip_default_plugins = false
skip_plugin_search   = false

[startup.plugins]
# Allows for defining shorthands
command        = { tasks = "doot.cmds.list_cmd:ListCmd" }

[shutdown]
notify    = { speak=false }
defaulted_values = { write=false, path=".defaulted_values.toml" }

[settings.commands]
[settings.commands.run]
tracker     = "default"
runner      = "default"
reporter    = "default"
report-line = []

[settings.commands.list]
hide    = []
aliases = { tasks=[] }

[logging]
[logging.stream]
level   = "user"
filter  = []
target  = "stdout"
format  = "{levelname:<8}  : {message}"

[logging.file]
level        = "trace"
filter       = ["jgdv"]
target       = "rotate"
format       = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})"
filename_fmt = "doot.log"

[logging.printer]
level        = "NOTSET"
colour       = true
target       = ["stdout", "rotate"]
format       = "{message}"
filename_fmt = "doot_printed.log"

[logging.extra]

[[locations]]
temp            = {path=".temp", cleanable=true}
templates       = "."
logs            = "{temp}/logs"
build           = "{temp}/build"
docs            = "docs"
data            = "data"
image_blacklist = {path="{temp}/image.blacklist", file=true}
