## pyproject.toml -*- mode: Toml -*-

## https://packaging.python.org/en/latest/
## https://packaging.python.org/en/latest/specifications/pyproject-toml/
[project]
name            = "Templates"
version         = "0.1.0"
description     = ""
readme          = "README.md"
requires-python = ">=3.11"
license         = {file = "LICENSE"}
keywords        = []
authors         = [
  {email = "jgrey4296@gmail.com", name  = "J Grey"}
]
classifiers     = [
  "Programming Language :: Python"
]

##-- dependencies
dependencies   = [
    "myst-parser>=4.0.1",
    "sphinx-autoapi>=3.6.0",
    "sphinx-rtd-theme>=3.0.2",
]

##-- end dependencies

##-- urls
[project.urls]
homepage      = "https://github.com/jgrey4296/"
documentation = "https://.readthedocs.io/en/latest/"
repository    = "https://github.com/jgrey4296/"
changelog     = "https://github.com/jgrey4296//spam/blob/master/CHANGELOG.md"

##-- end urls

# Tools #######################################################################

##-- git-cliff changelog
# https://git-cliff.org/docs/configuration
[tool.git-cliff.changelog]
header = "All notable changes to this project will be documented in this file."
body = "..."
footer = "<!-- generated by git-cliff -->"
# see [changelog] section for more keys

[tool.git-cliff.git]
conventional_commits = true
commit_parsers       = []
filter_commits       = false

[dependency-groups]
dev = [
    "pydot>=4.0.1",
    "python-statemachine>=2.5.0",
]
# see [git] section for more keys
##-- end git-cliff changelog
