#!/usr/bin/env python3
"""
$0
"""
# ruff: noqa:
# Imports
from __future__ import annotations

# ##-- stdlib imports
import argparse
import logging as logmod
import pathlib as pl
from re import Pattern
from sys import stderr, stdout
##-- end stdlib imports

from jgdv.logging.log_config import JGDVLogConfig
from jgdv.cli import ParseMachine

def main():
    args = parser.parse_args()
    verbosity = max(logmod.DEBUG, logmod.WARNING - (10 * (args.verbose or 0)))
    console_handler.setLevel(verbosity)

##-- ifmain
if __name__ == '__main__':
    main()

##-- end ifmain
