#!/usr/bin/env python3
"""

"""
# ruff.ignore.in.file PLR0912, BLE001

`(+snippet-expand "import.core")`

# ##-- 3rd party imports
import sh
import stackprinter
# ##-- end 3rd party imports

`(+snippet-expand "import.typing")`

`(+snippet-expand "setup.loglib")`

# Vars:

# Body:

`(+snippet-expand "ifmain")`
