#!/usr/bin/env python3
"""
$0
"""
`(+snippet-expand "test.ignores")`

# Imports
`(+snippet-expand "future.annotations")`

`(+snippet-expand "import.test")`

`(+snippet-expand "import.typing")`

`(+snippet-expand "setup.loglib")`

# Vars:

# Body:
`(+snippet-expand "pytest.suite")`
