#!/usr/bin/env python3
# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use pl.Path.resolve to make it absolute, like shown here.
#
import os
import sys
import pathlib as pl
sys.path.insert(0, pl.Path('../$1').resolve())

import $1

# (Relative to this file):
templates_path   = ['_templates']
html_static_path = ['_static']

# Relative to static dir, or fully qualified urls
html_css_files = ["custom.css"]
html_js_files  = []
# html_style = "custom.css"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['**/flycheck_*.py', "**/__tests/*"]

# -- Project information -----------------------------------------------------

project   = '$1'
copyright = '2022, `user-full-name`'
author    = '`user-full-name`'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.doctest',
              'sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.napoleon',
              'sphinx.ext.extlinks',
              # 'sphinx_rtd_theme'
              ]


##-- autosummary
autosummary_generate = True
##-- end autosummary

##-- autodoc
autodoc_default_options = {
    'members'       : True,
    'undoc-members' : True,
    # 'private-members': True,
    # 'special-members': True,
    'inherited-members': True,
    'show-inheritance' : True,
    }
add_module_names = False
autodoc_inherit_docstrings = True

##-- end autodoc

# -- Options for HTML output -------------------------------------------------

html_theme         = 'alabaster' # 'sphinx_rtd_theme
html_theme_options = {}
