# -*- mode:conf-toml; -*-
[settings.general]
notify                   = { say-on-exit = false }
loaders                  = { commands="default", task="default", parser="default"}
location_check           = { make_missing=true }

[settings.tasks]
sources   = ["{template_tasks}/global", "{template_tasks}/android_tasks"]
core      = []
sleep     = { tasks=0.2, subtask=1, batch=1 }
max_steps = 100_000

[settings.commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = [] }

[plugins] # Allows for defining shorthands
command        = { tasks = "doot.cmds.list_cmd:ListCmd" }

[logging]
stream  = { level="WARNING", filter=[],                 target="stdout", format="{levelname:<8} : {message}"  }
file    = { level="DEBUG",   filter=["tomlguard"],      target="rotate", format="{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})", filename_fmt="_cache_/doot/logs/doot.log" }
printer = { level="NOTSET",  colour=true,               target=["stdout", "rotate"], format="{message}", filename_fmt="_cache_/doot/logs/doot_printed.log" }

[logging.subprinters]
default       = {level="WARNING"}
shutdown      = {level="WARNING",    format="Shutdown: {message}", target="stdout"}
cmd           = {level="INFO"}
task          = {level="INFO" }
header        = {level="INFO" }
task_header   = {level="INFO"}

[[locations]]
templates      = {loc="~/.config/.templates", normOnLoad=true}
temp           = {loc="_cache_/doot/temp",  cleanable=true}
build          = {loc="_cache_/doot/build", cleanable=true}
logs           = "{temp}/logs"
template_tasks = "{templates}/doot"
records        = "{templates}/.maintenance"
