# -*- mode:conf-toml; -*-

[startup]
doot-version      = "1.1"
loaders           = { commands="default", task="default", parser="default" }
sources           = { tasks=["{template_tasks}/global", "{template_tasks}/android_tasks"], code=[] }

[shutdown]
notify            = { speak=false }
defaulted_values  = { write=false }

[settings.commands]
run = { tracker = "default", runner = "default", reporter= "default", report-line = [] }

[plugins] # Allows for defining shorthands
command        = { tasks = "doot.cmds.list_cmd:ListCmd" }

[logging]

[logging.stream]
level   = "user"
filter  = []
target  = "stdout"
format  = "{levelname:<8}  : {message}"

[logging.file]
level        = "trace"
filter       = ["jgdv"]
target       = "rotate"
format       = "{levelname:<8} : {message:<20} :|: ({module}.{lineno}.{funcName})"
filename_fmt = "_cache_/doot/logs/doot.log"

[logging.printer]
level        = "NOTSET"
colour       = true
target       = ["stdout", "rotate"]
format       = "{message}"
filename_fmt = "_cache_/doot/logs/doot_printed.log"

[[locations]]
templates      = "~/.config/.templates"
temp           = "clean::>_cache_/doot/temp"
build          = "clean::>_cache_/doot/build"
logs           = "{temp}/logs"
template_tasks = "{templates}/doot"
records        = "{templates}/.maintenance"
