## backup.toml -*- mode: toml -*-
doot-version = "1.1"
# TODO use rsync --archive --progress --partial
[[locations]]
data     = "/media/john/data"
backup_1 = "/media/john/big_ex"
backup_2 = "/media/john/BackupSD"
backup_3 = "/media/john/LargeBackup"

[[tasks.backup]]
name          = "+.assets"
doc           = ["Backup assets"]
exts          = []
recursive     = true
roots         = ["{data!p}/assets"]
shadow_roots  = ["{backup_1!p}/assets", "{backup_2!p}/assets"]
actions       = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={insert=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions   = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]


[[tasks.backup]]
name          = "+.datasets"
doc           = ["Backup assets"]
exts          = []
recursive     = true
roots         = ["{data!p}/datasets"]
shadow_roots  = ["{backup_1!p}/datasets", "{backup_2!p}/datasets"]
actions       = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={insert=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions                = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]

[[tasks.backup]]
name          = "+.pictures"
doc           = ["Backup assets"]
exts          = []
recursive     = true
roots         = ["{backup_1!p}/pictures"]
shadow_roots  = ["{backup_2!p}/pictures"]
actions       = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={insert=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions                = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]

[[tasks.backup]]
name     = "pdfs"
actions  = [{do="log", msg="Use bibliography tasks to backup pdfs"}]
