## backup.toml<2> -*- mode: conf-toml -*-

[[locations]]
data     = "/media/john/data"
backup_1 = "/media/john/big_ex"
backup_2 = "/media/john/BackupSD"

[[tasks.backup]]
name                       = "assets"
version                    = "0.1"                                                       # <str>
doc                        = ["Backup assets"]
ctor                       = "job"             # <type>
exts                       = []                                  # <list[str]>
recursive                  = true                                # <bool>
roots                      = ["{data}/assets"]                    # <list[str|pl.Path]>  Places the globber will start
shadow_roots               = ["{backup_1}/assets", "{backup_2}/assets"]
actions = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions                = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]


[[tasks.backup]]
name                       = "datasets"
version                    = "0.1"                                                       # <str>
doc                        = ["Backup assets"]
ctor                       = "job"             # <type>
exts                       = []                                  # <list[str]>
recursive                  = true                                # <bool>
roots                      = ["{data}/datasets"]                    # <list[str|pl.Path]>  Places the globber will start
shadow_roots               = ["{backup_1}/datasets", "{backup_2}/datasets"]
actions = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions                = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]

[[tasks.backup]]
name                       = "pictures"
version                    = "0.1"
doc                        = ["Backup assets"]
ctor                       = "job"
exts                       = []
recursive                  = true
roots                      = ["{backup_1}/pictures"]
shadow_roots               = ["{backup_2}/pictures"]
actions = [
    {do="job.walk", update_="files"},
    {do="job.expand", from_="files", update_="tasks", inject={replace=["fpath"]}, template_="sub_actions"},
    {do="job.inject.path.elements", onto_="tasks",  key_="fpath"},
    {do="dootle.utils.multi_shadow:InjectMultiShadow", onto_="tasks", key="rpath"},
    {do="job.queue", from_="tasks"},
]
sub_actions                = [
    {do="dootle.utils.multi_shadow:MultiBackupAction", from_="fpath", pattern="{shadow_path!p}/{fname}"}
]
