## maintenance.toml -*- mode: conf[TOML] -*-

[[locations]]
records = ".maintenance"

[[tasks.chore]]
name    = "versions"
version = "0.1"
ctor    = "task"
doc     = ["Update the list of installed software versions"]
depends_on = ["chore::_.apt.versions", "chore::_.snap.versions",
               "chore::_.mamba.versions", "chore::_.rust.versions",
               "chore::_.tex.versions", "chore::_.git",
               # "chore::_.cron",
               ]

[[tasks.chore]]
name    = "_.apt.versions"
version = "0.1"
ctor    = "task"
actions = [
        {do="shell", args=["apt", "list", "--installed"], update_="versions", notty=true},
        {do="write!", from_="versions", to="{records}/apt.versions"},
]

[[tasks.chore]]
name    = "_.snap.versions"
version = "0.1"
ctor    = "task"
actions = [
        {do="shell", args=["snap", "list"], update_="versions", notty=true},
        {do="write!", from_="versions", to="{records}/snap.versions"},
]

[[tasks.chore]]
name    = "_.mamba.versions"
version = "0.1"
ctor    = "task"
actions = [
        { do="dootle.python.mamba:MambaEnv", env="default", update_="default"},
        { do="shell", args=["mamba", "info"], shenv_="default", update_="info"  },
        { do="write!", from_="info", to="{records}/mamba.info"},
        { do="shell", args=["pip", "list"], shenv_="default", update_="pip"  },
        { do="write!", from_="pip", to="{records}/mamba.versions"},
]

[[tasks.chore]]
name    = "_.rust.versions"
version = "0.1"
ctor    = "task"
actions = [
        { do="shell", args=["rustup", "show"], update_="rustup"  },
        { do="write!", from_="rustup", to="{records}/rustup.info"},
]

[[tasks.chore]]
name    = "_.tex.versions"
version = "0.1"
ctor    = "task"
actions = [
        { do="shell", args=["tlmgr", "info", "--only-installed", "-data", "name,cat-version,localrev,shortdesc"], update_="tex"  },
        { do="write!", from_="tex", to="{records}/tex.versions"},
]

[[tasks.chore]]
name    = "_.git"
version = "0.1"
ctor    = "task"
actions = [
        {do="shell", args=["git", "--version"], update_="gitinfo" },
        {do="write!", from_="gitinfo", to="{records}/git.version"},
]

[[tasks.chore]]
name = "_.cron"
version = "0.1"
ctor = "task"
actions = [
        {do="shell", args=["crontab", "-l"], update_="cron"},
        {do="write!", from_="cron", to="{records}/cron.backup"},
]
