# mastodon.toml<2> -*- mode: conf-toml -*-

[[locations]]
mastodon_secrets = {file="~/.config/secrets/bots/bkmkorg.toml"}
image_temp       = "{temp}/images/"
all_bib          = "/media/john/data/github/bibliography/main/"
image_whitelist  = {loc="~/.config/secrets/bots/whitelist", normOnLoad=true}

[[tasks.mast]]
name                 = "post-image"
version              = "0.1"                # <str>
ctor                 = "task" # <type>
doc                  = ["TODO: Post a whitelisted image to mastodon"] # <list[str]>
actions              = []                   # <list[Any]>
# TODO : read from image_whitelist, select, post

[[tasks.mast]]
name                 = "bibtex"
version              = "0.1"                # <str>
ctor                 = "job" # <type>
doc                  = ["Maybe Post a formatted bibtex citation to mastodon"] # <list[str]>
select_limit         = 1
roots                = ["{all_bib}"]                # <list[str|pl.Path]>  Places the walker will start
exts                 = [".bib"]                   # <list[str]>
cleanup         = [
    { do="post.get", entries="-" },
    { do="taskcode.soc_media:format_for_mastodon", from_="entries", update="text"},
    { do="dootle.mastodon.actions:MastodonSetup" },
    { do="dootle.mastodon.actions:MastodonPost", from_="text" },
]
actions = [
    {do="job.walk",   update_="files"}, # walk,
    {do="job.expand", from_="files", update_="tasks", inject={copy=["fpath"]}, template_="sub_actions"},
    {do="job.limit",  count_="select_limit"},
    {do="job.queue",  from_="tasks"}, # queue
]
sub_actions          = [
    { do="taskscode.bibtex:build_parse_stack",  update_="parse_stack"},
    { do="dootle.bibtex.v2:BibtexInitAction",  update_="bib_db"},
    { do="dootle.bibtex.v2:BibtexLoadAction",  from_="fpath", update_="bib_db", parse_stack_="parse_stack" },
    { do="taskscode.bibtex:select_one_entry", from_="bib_db", update_="entry"},
    { do="post.put", args=["entry"] },
]
