# dnsmasq.conf -*- mode: conf-unix -*- 

domain-needed
bogus-priv
no-resolv
no-poll

interface=lo
interface=wlp2s0

bind-interfaces

# Domain settings
#
domain=jg
expand-hosts

addn-hosts=/media/john/data/github/_templates/etc/dnsmasq.hosts

# server=
