## pelican.toml -*- mode: toml -*-
doot-version = "1.1"

[[locations]]
pelicanpy = "file::>pelicanconf.py"
pelican   = "file::>pelican.toml"

[[tasks.pelican]]
name        = "build"
doc         = ["Run pelican"]
depends_on  = ["{pelican!p}"]
actions     = [
   { do="touch", args=["{pelicanpy!p}"] },
   { do="shell!", args=["pelican", "."] },
   { do="delete!", args=["{pelicanpy!p}"] },
]

[[tasks.pelican]]
name                 = "listen"
doc                  = ["Run pelican"]                          
depends_on           = ["{pelican!p}"]                   
actions              = [
                     { do="touch", args=["{pelicanpy!p}"] },
                     { do="shell!", args=["pelican", "--listen", "--autoreload", "{.!p}"] }
]
