#!/usr/bin/env python3
"""
TEST File updated
$0
"""
`(+snippet-expand "test.ignores" nil 'py-test-minor-mode)`
# Imports
`(+snippet-expand "future.annotations")`

`(+snippet-expand "import.test" nil 'py-test-minor-mode)`

##--|
from .. import
##--|

`(+snippet-expand "import.typing")`

`(+snippet-expand "setup.loglib")`

# Vars:

# Body:
`(+snippet-expand "pytest.suite" nil 'py-test-minor-mode)`
