#!/usr/bin/env bash
# `(f-filename (buffer-file-name))` -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
[[ -e "$POLYGLOT_SRC/lib/lib.bash" ]] && source "$POLYGLOT_SRC/lib/lib.bash"
# shellcheck disable=SC1091
[[ -e "$(poly-dir)/task-util.bash" ]] && source "$(poly-dir)/task-util.bash"

