
[[locations]]
tools = "tools"
home  = "~"
tex   = "~/.local/texlive/current"

[[tasks.setup]]
name                 = "symlinks"
version              = "0.1"                # <str>
doc                  = ["setup symlinks to templates"]                   # <list[str]>
ctor                 = "task"               # <str>
mixins               = []                   # <list>               mix in additional capabilities
print_levels = {execute="INFO"}
actions              = [
                     # Main
                     {do="link!", link="{home}/.asdfrc",             to="{tools}/asdfrc"},
                     {do="link!", link="{home}/.cabalrc",            to="{tools}/cabal.conf"},
                     {do="link!", link="{home}/.cookiecutterrc",     to="{tools}/cookiecutterrc"},
                     {do="link!", link="{home}/.gemrc",              to="{tools}/gemrc"},
                     {do="link!", link="{home}/.ghci",               to="{tools}/ghci"},
                     {do="link!", link="{home}/.gitconfig",          to="{tools}/gitconfig"},
                     {do="link!", link="{home}/.globalrc",           to="{tools}/globalrc"},
                     {do="link!", link="{home}/.inputrc",            to="{tools}/inputrc"},
                     {do="link!", link="{home}/.lldbinit",           to="{tools}/lldbinit.conf"},
                     {do="link!", link="{home}/.mailrc",             to="{tools}/mailrc"},
                     {do="link!", link="{home}/.mail",               to="{tools}/mailutils.conf"},
                     {do="link!", link="{home}/.mbsyncrc",           to="{tools}/mbsyncrc.linux"},
                     {do="link!", link="{home}/.npmrc",              to="{tools}/npmrc"},
                     {do="link!", link="{home}/.tmux.conf",          to="{tools}/tmux.conf"},
                     {do="link!", link="{home}/.ExifTool_config",    to="{tools}/ExifTool_config"},
                     {do="link!", link="{home}/.gitignore_global",   to="{tools}/gitignore_global"},
                     {do="link!", link="{home}/.gradle_properties",  to="{tools}/gradle.properties"},
                     {do="link!", link="{home}/.tool-versions",      to="{tools}/asdf_tool_version"},
                     {do="link!", link="{home}/.wgetrc",             to="{tools}/wgetrc"},
                     {do="link!", link="{home}/.pam_environment",    to="{tools}/pam_environment"},

                     {do="link!", link="{home}/doot.toml",           to="doot/home_doot.toml"},
                     {do="link!", link="{home}/.vimrc",              to="vim/vimrc"},
                     {do="link!", link="{home}/.ispell_english",     to="ispell/ispell_english"},
                     {do="link!", link="{home}/.aspell.conf",     to="ispell/aspell.conf"},
                     {do="link!", link="{home}/.mambarc",            to="python/condarc"},

                     # subdirs
                     {do="link!", link="{home}/.ssh/config",                     to="{tools}/ssh_config"},
                     {do="link!", link="{home}/.config/gdb/gdbinit",             to="{tools}/gdbinit"},
                     {do="link!", link="{home}/.config/gh/config.yml",           to="{tools}/github_config.yml"},
                     {do="link!", link="{home}/.config/gpg/gpg-agent.conf",      to="{tools}/gpg-agent.linux.conf" },
                     {do="link!", link="{home}/.config/calibre/global.py.json",  to="{tools}/calibre/global.py.json"},
                     {do="link!", link="{home}/.config/user-dirs.dirs",          to="{tools}/user-dirs.dirs"},
                     {do="link!", link="{home}/.config/matplotlib/matplotlibrc", to="python/matplotlibrc"},
                     {do="link!", link="{home}/.config/switch-to-firefox.bash",  to="bash/shortcuts/switch-to-firefox.bash"},
                     {do="link!", link="{home}/.config/switch-to-tor.bash",  to="bash/shortcuts/switch-to-tor.bash"},

                     {do="link!", link="{home}/.cache/cargo/config.toml",        to="{tools}/cargo_config.toml"},
                     # Tex
                     {do="link!", link="{tex}/texmf.cnf",            to="tex-config/texmf.cnf.linux"},
                     {do="link!", link="{tex}/texmfcnf.lua",         to="tex-config/texmfcnf.lua.linux"},

                     # Apt - needs permissions
                     # {do="link!", link="/etc/apt/preferences.d/disallow", to="{tools}/apt/disallow"},
]                   # <list[Any]>

[[tasks.setup]]
name = "bash"
version = "0.1"
ctor = "task"
actions = [
        {do="link!", link="{home}/.bashrc",       to="bash/interactive.bash"},
        {do="link!", link="{home}/.bash_logout",  to="bash/logout.bash"},
        {do="link!", link="{home}/.bash_profile", to="bash/login.bash"},
        {do="link!", link="{home}/.profile",      to="bash/profile.linux.bash"},

]

[[tasks.setup]]
name    = "dirs"
version = "0.1"
ctor    = "task"
actions = [
        {do="dir!", args=["{home}/.config/secrets", "{home}/.cache", "{home}/.local/bin"]}

]

[[tasks.setup]]
name    = "misc"
version = "0.1"
ctor    = "task"
actions = [
        {do="touch", file="{home}/.browsers"}
]
