#!/usr/bin/env bash
#  cargo-record-versions -*- mode: sh -*-

function record_versions () {
    set -o nounset
    local TARGET="$PROJ_ROOT/.maintenance"

    echo "Recording System State to: $TARGET"

    # apt
    echo "... apt"
    apt list --installed > "$TARGET/apt.versions"
    apt-add-repository --list > "$TARGET/apt.repos"

    # snap
    echo "... snap"
    snap list > "$TARGET/snap.versions"

    # flatpak
    echo "... flatpak"
    flatpak list --all > "$TARGET/flatpak.versions"
    flatpak remotes > "$TARGET/flatpak.remotes"

    # git
    echo "... git"
    git --version > "$TARGET/git.version"

    # cron
    echo "... cron"
    crontab -l > "$TARGET/cron.backup"

    # rust
    echo "... rust"
    rustup show -v > "$TARGET/rustup.info"

    # asdf
    echo "... asdf"
    asdf info > "$TARGET/asdf.info"
    asdf list > "$TARGET/asdf.plugins"

    # android
    echo "... android sdkmanager"
    sdkmanager --list_installed > "$TARGET/android.versions"

    # dotnet
    echo "... dotnet"
    dotnet --info > "$TARGET/dotnet.info"

    # uv tools
    echo "... uv"
    uv tool list > "$TARGET/uv.tools"

    # .local
    echo "... local"
    ls -l "$HOME/.local" > "$TARGET/local.installs"
}

record_sdkman () {
    set +o nounset
    # sdkman
    local TARGET="$PROJ_ROOT/.maintenance"
    echo "... jvm sdkman"
    init_sdkman
    sdk current > "$TARGET/sdkman.versions"
}

record_versions
record_sdkman
