# #  python-publish.yml -*- mode: YAML -*-

# Actions to build and upload to pypi
# Actions Used:
# https://github.com/astral-sh/setup-uv
# https://github.com/actions/checkout/
# https://github.com/actions/upload-artifact
# https://github.com/actions/download-artifact
# https://github.com/pypa/gh-action-pypi-publish

name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch: # for manual triggers
    
permissions:
  contents: read

# --------------------------------------------------
jobs:
  test:
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - uses: actions/checkout@v4
      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
      - name: setup
        run: |
          uv lock --no-sources
          uv env
          uv sync --frozen --group test
      - name: test
        run: |
          uv run tox -e test
  
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    environment: publishing
    steps:
      - name: Build package
        run: |
          mkdir --parents .temp/egg-info
          uv build .
      - name: Store dist packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    environment: 
      name: publishing
      url: https:://pypi.org/p/jgdv
    permissions:
      id-token: write
    steps:
      - name: get dists
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      - name: push
        uses: pypa/gh-action-pypi-publish@release/v1
      
