## backup.toml<2> -*- mode: conf-toml -*-

[[locations]]
backup       = "{temp}/backup"
data_drive   = "/media/john/data"
backup_drive = "/media/john/big_ex"
pdf_source   = "{data_drive}/library/pdfs"
pdf_bkup     = "{backup_drive}/library/pdfs"

# TODO movies
# TODO images

[[tasks.backup]]
name                       = "pdfs"
version                    = "0.1"                                                       # <str>
doc                        = ["Backup pdf library"]
ctor                       = "job"             # <type>
clean_locs                 = ["{pdf_bkup}"]
print_levels               = {build="WARNING", action="WARNING", execute="INFO"} # <Dict: {'build', 'action', 'sleep', 'head', 'execute'}>
exts                       = []                                  # <list[str]>
recursive                  = true                                # <bool>
roots                      = ["{pdf_source}"]                    # <list[str|pl.Path]>  Places the globber will start
shadow_root                = "{pdf_bkup}"
head_actions               = [{do="doot.actions.postbox:SummarizePostAction", full=false}]
sub_actions                = [
                     {do="dir!", args=["{shadow_path}"] },
                     {do="backup!", from_="fpath", to="{shadow_path}/{fname}"}
]
actions = [
        {do="job.walk", update_="files"}, # walk,
        {do="job.expand", from_="files", update_="tasks", inject={copy=["fpath"]}, base_="sub_actions"},
        {do="job.inject.shadow", onto_="tasks" }, # shadow
        {do="job.queue", from_="tasks"}, # queue
        {do="job.queue.head", base_="head_actions"},
]
