#!/usr/bin/env bash
#  cargo-setup-system -*- mode: sh -*-

echo "TODO: setup system"

function setup_config () {
    # XDG_CONFIG_HOME
}

function setup_cache () {
    # XDG_CACHE_HOME
}


function setup_symlinks () {

}

function setup_tools () {

}

function setup_bash () {

}

function setup_git () {

}

function setup_nu () {

}

function setup_asfd () {

}

function setup_sdkman () {

}

function setup_android () {

}

function setup_flatpak () {

}

function setup_rust () {

}

function setup_go () {

}
