#!/usr/bin/env bash
# chores.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

current_script_path="${BASH_SOURCE[0]}"
current_dir=$(dirname "$current_script_path")

echo "... Sourcing"
source "$current_dir/chores-lib"

