#!/usr/bin/env bash
# get-audio.bash -*- mode: sh -*-
set -o errexit
set -o nounset
set -o pipefail

target=$(head -n 1 "$PWD/todo")
count=$(cat "$PWD/todo" | wc -l)
echo "* Target 1/$count: $target"
yt-dlp -t mp3 "$target"
tail -n +2 "$PWD/todo" > "$PWD/.todo"
mv "$PWD/.todo" "$PWD/todo"
echo "* Remaining todo: " "$(cat "$PWD/todo" | wc -l)"
notify-send -e "Finished Audio Download" 2>/dev/null
