#!/usr/bin/env bash
#  jg_promp_update -*- mode: sh -*-
# setting up the prompt:
# from https://unix.stackexchange.com/questions/216953

BASE_ENV=""
PROMPT_INFO=()
SHELL_DEPTH="${PROMPT_NUM:-1}"
SEP="."

function append () {
    if [[ "${#PROMPT_INFO}" = 0 ]]; then
        PROMPT_INFO+=("$1")
    else
        PROMPT_INFO+=("$SEP")
        PROMPT_INFO+=("$1")
    fi
}

# Get the location:
PATH_SEGMENT=$(pwd | sed -r 's/.+?\/(.+?\/.+?)/...\/\1/')

# Get the depth:
[[ "${SHELL_DEPTH}" -gt 1 ]] || SHELL_DEPTH="⟘"

append "$SHELL_DEPTH"

# See whats activated:
[[ -z "${TMUX:-}" ]]            || append "TMUX"

[[ -z "${INSIDE_EMACS:-}" ]]    || append "emacs"

[[ -z "${DIRENV_DIR:-}" ]]      || append "direnv"

[[ -z "${ASDF_DATA_DIR:-}" ]]   || append "asdf"

[[ -z "${SDKMAN_PLATFORM:-}" ]] || append "sdkman"


if [[ -n "${VIRTUAL_ENV:-}" ]]; then
    BASE_ENV=$(dirname "$VIRTUAL_ENV");
    BASE_ENV=$(basename "$BASE_ENV";)
    append "venv(${BASE_ENV})"
elif [[ -n "${CONDA_DEFAULT_ENV:-}" ]]; then
    append "mamba(${CONDA_DEFAULT_ENV:-})"
fi


# Assemble it
echo "${PROMPT_INFO[@]}"
echo "${PATH_SEGMENT}"
exit 0
