#!/usr/bin/env bash
# jg-test.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail


echo "All Args: " "$@"

echo "Last Arg: " "${@: -1}"

value=0

[[ "$value" -lt 5 ]] && (( value+=1 ))
[[ "$value" = 0 ]] || value=$(( value + 1 ))

echo "Value is: $value"
