#!/usr/bin/env bash
# jg-test.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

# shellcheck disable=SC1091
source "$HOME/_cache_/asdf/plugins/polyglot/polyglot/lib/lib-util.bash"

val=(a b c)
echo "Val: ${val[@]}, ${val[1]}"

exit
echo "Arg: $0 , Arg: $1, Arg: $2"

exit
rst=("${@:1}")
echo "Rest: ${@:1}"
exit

echo "All Args: " "$@"

echo "Last Arg: " "${@: -1}"

value=0

[[ "$value" -lt 5 ]] && (( value+=1 ))
[[ "$value" = 0 ]] || value=$(( value + 1 ))

echo "Value is: $value"

# read -p "Test Prompt: " blah

# echo "Got : $blah"

# if ( ! aweg 2>/dev/null ); then
#     echo "no aweg"
# fi

pushctx "blah" >/dev/null
pushctx "bloo" >/dev/null

VALS=("a" "b")

VALS+=("blah")
VALS+=("bloo")
VALS+=("aweg")

echo "first: ${VALS[0]}"
echo "${VALS[*]::${#VALS[@]}-1} : ${VALS[-1]}"
echo "${VALS[@]:1}"

# print-env-failures "${VALS[@]}"

# TVAL="blah_mono"
# case "$TVAL" in
#     *_mono) echo "is mono";;
#     *) echo "is not mono";;
# esac

# T2VAL="${TVAL/_mono/}"
# echo "t2val: $T2VAL"

# function blah (){
#     echo "blahaweg"
# }

# AVAL=$($T2VAL | sed 'p; p')
# echo "aval is: $AVAL"

function blah () {
    echo "value"
    echo "bloo"
    echo "blee"
}
# { echo "blah"; echo "bloo"; }
blah

readarray -t myvar <<< "$(blah)"
for val in "${myvar[@]}"
do
    echo "- '$val'"
done


values="blah
bloo
blee
"

fvals=$(< "$HOME/jgtestvals")

echo "Values: ${values}"
echo "fvals: ${fvals}"

joined="${values}
${fvals}"
joined+=$(env | grep "POLYGLOT" | sort | uniq)

echo "--"
echo "${joined}" | sort | sed '/\S/!d'
echo "--"
