#!/usr/bin/env bash
# quick-server.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

DIR="${1:-$PWD}"
ADDR="${2:-192.68.1.247}"
PORT="${3:-80}"
# sudo ufw allow proto tcp from any to 192.168.1.247 port 8000

echo "----Starting Quickserver"
echo "- Dir: $DIR"
echo "- Address: $ADDR"
echo "- Port: $PORT"
( python \
    -m http.server \
    -d "$DIR"
    -b "$ADDR" "$PORT"
)
