#!/usr/bin/env bash
# backup-secrets.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

echo -e "=====\nBacking up Secrets\n====="
base="$XDG_CONFIG_HOME/secrets"
target="$base/secrets.zip"

pushd "$base" || { echo "failed to pushd: $base"; exit 1; }

pushd "gnupg" || { echo "failed to pushd: gnupg"; exit 1; }
echo "- gpg:"
keys-backup
popd || exit 1
zip --grow -r  "$target" gnupg

echo "- ssh:"
zip --grow -r  "$target" ssh

echo "- mail:"
zip --grow -r  "$target" mail

echo "- tokens:"
zip --grow -r  "$target" tokens

echo "- passwords:"
zip --grow "$target" "passwords.asc"

echo "- other:"
zip --grow -r  "$target" other

popd || exit 1
