#!/usr/bin/env bash
# init-ssh.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

base="$XDG_CONFIG_HOME/secrets"
echo "Initialising secrets"

echo "- GPG"
for file in "$base/gnupg"/*
do
    [[ -f "$file" ]] && gpg --import "$file"
done

echo ""
echo "- SSH"
# ssh-add -D
for file in "$base/ssh"/*
do
    echo "- Adding $file"
    statres=$(stat -c "%a" "$file")
    if [[ -f "$file" ]] && [[ "$statres" = "600" ]]; then
        SSH_ASKPASS_REQUIRE="never" ssh-add "$file"
    fi
done
