#!/usr/bin/env bash
# send-media.bash -*- mode: sh -*-
#set -o errexit
set -o nounset
set -o pipefail

BASE="john@MEDIA:/media"
# TODO add a help flag
args=("$@")
target="${args[0]}"
rest=("${args[@]:1}")


echo "* Sending $rest to $target"
( scp -r "${rest[@]}" "${BASE}/${target}" ) && notify-send -e "Finished sending $rest to media" 2>/dev/null
