#!/usr/bin/env bash
# ssh-pubkey.bash -*- mode: sh -*-
# Get the public key of a secret key

#set -o errexit
set -o nounset
set -o pipefail

base="$XDG_CONFIG_HOME/secrets/ssh"

case "${1:-}" in
    -a|--all)
        for file in "$base"/*
        do
            ssh-keygen -f "$file" -y
        done
        exit 0
        ;;
    *) ;;
esac

for key in "$@"
do
    [[ -f "$base/$key" ]] || { echo "Key Not Found: $key"; exit 1; }
    ssh-keygen -f "$base/$key" -y
done
