# #  book.toml -*- mode: TOML -*-
# https://rust-lang.github.io/mdBook/guide/creating.html
[book]
title         = "{{cookiecutter.proj_name}}"
authors       = ["{{cookiecutter._author}}"]
description   = ""
src           = "src/_docs"
language      = "en"
multilingual  = false

[rust]
edition       = "2024"

[build]
build-dir                  = ".temp/book"
create-missing             = false
use-default-preprocessors  = true
extra-watch-dirs           = []

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = []

[output.html.search]


