## docs.toml -*- mode: toml -*-
doot-version = "0.13"

# autodoc : https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html
# apidoc  : https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html
# autogen : https://www.sphinx-doc.org/en/master/man/sphinx-autogen.html


[[locations]]
doc_src = "docs"
doc_out = "{temp}/docs"

[[tasks.pydocs]]
name       = "export"
warn       = false
depends_on = [{task="pydocs::build", inject={now=["warn"]}}]

[[tasks.pydocs]]
name        = "build"
doc         = ["build sphinx project documentation"]
cli         = [
    {name="warn", type="bool", default=true},
]
ctor        = "task"
doc_builder = "html"
env_name    = "doot-dev"
depends_on  = []
setup       = [
    { do="dootle.python.mamba:MambaEnv", env_="env_name", update_="env"},
    { do="installed?", args=["sphinx-build"], env_="env"},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    # --conf-dir {!p} : directory for conf.py
    { do="shell", env_="env", args=["sphinx-build",
    # "--verbose", "--verbose", "--nitpicky", "--write-all",
    "--warning-file", "{logs!p}/sphinx.log",
    "--define", "keep_warnings={warn}",
    "--builder", "{doc_builder}",
    "{doc_src!p}", "{doc_out!p}",
    ]},

    {do="taskcode.refresher:refresh_firefox"},
    ]
cleanup = []

[[tasks.pydocs]]
name        = "test"
doc         = ["run sphinx doctest"]
ctor        = "task"
doc_builder = "doctest"
env_name    = "distributor"
setup       = [
    { do="dootle.python.mamba:MambaEnv", env_="env_name", update_="env"},
    { do="installed?", args=["sphinx-build"], env_="env"},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    # --conf-dir {!p} : directory for conf.py
    { do="shell", args=["sphinx-build", "--warning-file", "{logs!p}/sphinx.log", "--builder", "{doc_builder}", "{doc_src!p}", "{doc_out!p}"] },


]

[[tasks.pydocs]]
name        = "build.file"
doc         = ["build sphinx project documentation"]
cli         = [{name="fpath", prefix=1, type="str", default=""}]
ctor        = "task"
doc_builder = "html"
env_name    = "doot-dev"
setup       = [
    { do="dootle.python.mamba:MambaEnv", env_="env_name", update_="env"},
    { do="installed?", args=["sphinx-build"], env_="env"},
    { do="exists?", args=["{doc_src!p}/conf.py"] },
]
actions = [
    {do="log", msg="Building for: {fpath}"},
    {do="log", msg="sphinx-build --builder {doc_builder} --warning-file {logs!p}/sphinx.log --keep-going --show-traceback {doc_src!p} {doc_out!p} {fpath}"},
    { do="shell", env_="env", args=["sphinx-build",
     "--builder", "{doc_builder}",
    "--warning-file", "{logs!p}/sphinx.log",
    "--keep-going", "--show-traceback",
     "{doc_src!p}", "{doc_out!p}",
     "{fpath}"]},

     {do="taskcode.refresher:refresh_firefox"},

     ]
cleanup = []
