
[[tasks.precommit]]
name                 = "validate"
version              = "0.1"                # <str>
doc                  = ["Validate a commit message.", "Runs in stage commit-msg"]
cli                  = [
                     { name="msgfile",   default="", type="str", positional=true },
]
ctor                 = "task"               # <str>
actions              = [
                     {do="read", from_="msgfile", update_="text"},
                     {do="taskcode.precommit:validate", from_="text"}
]

[[tasks.precommit]]
name         = "Run a task for "
doc          = [""]
ctor         = "job"
mixins       = ["job:expander"]
cli          = [
             { name="files",   type="list", default=[], positional=true }
]
print_levels = { head="INFO", build="DEBUG", execute="INFO", sleep="WARNING", action="WARNING" }
retriever    = "doot.utils.retrievers:cli_retriever"
sub_task      = "TODO"
