# Symlink to $CARGO_HOME/config.toml
# https://doc.rust-lang.org/cargo/
# Rust Package management

# paths = ["/path/to/override"] # path dependency overrides

[alias]     # command aliases
# b = "build"
# c = "check"
# t = "test"
# r = "run"
# rr = "run --release"
# recursive_example = "rr --example recursions"
# space_example = ["run", "--release", "--", "\"command list\""]

[build]
jobs = 1                      # number of parallel jobs, defaults to # of CPUs

[doc]
browser = "firefox"

[env]
# ENV_VAR_NAME = "value"
# ENV_VAR_NAME_2 = { value = "value", force = true }
# ENV_VAR_NAME_2 = { value = "relative/path", relative = true }

[cargo-new]
vcs = "git" 

[http]
# debug = false               # HTTP debugging
# proxy = "host:port"         # HTTP proxy in libcurl format
# timeout = 30                # timeout for each HTTP request, in seconds

[install]
# root = "/some/path"         # `cargo install` destination directory

[term]
# quiet = false          # whether cargo output is quiet
# verbose = false        # whether cargo provides verbose output
# color = 'auto'         # whether cargo colorizes output
# progress.when = 'auto' # whether cargo shows progress bar
# progress.width = 80    # width of progress bar
