## tox.toml -*- mode: toml-mode -*-
# https://tox.wiki/en/4.28.4/user_guide.html
# https://github.com/tox-dev/tox-uv
# String substitution: "{[<table>]<key>}"
requires                   = ["tox>=4", "tox-uv>=1"]
env_list                   = ["docs"]
work_dir                   = ".temp/tox/work"
temp_dir                   = ".temp/tox/temp"
skip_missing_interpreters  = false

[env_run_base]
description          = "base_env"
runner               = "uv-venv-lock-runner"
uv_sync_flags        = ["--no-editable", "--no-sources"]
allowlist_externals  = ["echo", "mkdir"]
set_env.PKGNAME      = {replace="env", name="PKGNAME", default="jgdv"}

[env.docs]
description   = "build documentation"
skip_install  = true
set_env = [
    {replace="ref", of=["env_run_base", "set_env"]},
    {CONFDIR  = {replace="env", name="CONFDIR",  default="./jgdv/_docs/"}},
    {OUTDIR   = {replace="env", name="OUTDIR",   default="./.temp/docs/"}},
    {DOCTREE  = {replace="env", name="DOCTREE",  default="./.temp/docs/.doctrees/"}},
]
commands      = [
    ["echo", "Building Documentation to:", "{env:OUTDIR}"],
    ["echo", "Doctrees to:", "{env:DOCTREE}"],
    ["echo", "Config in:", "{env:CONFDIR}"],
    ["uv", "run", "--frozen", "sphinx-build",
    # "-q",
    # "--fresh-env",
    "--conf-dir", "{env:CONFDIR}",
    "--doctree-dir", "{env:DOCTREE}",
    "--warning-file", "./.temp/logs/sphinx.log",
    "--builder", "html",
     "./{env:PKGNAME}",
     "{env:OUTDIR}",
    {replace="posargs", default=[], extend=true}
    ]
]

