## util.toml -*- mode: toml -*-
doot-version = "1.1"

[[tasks.util]]
name    = "count"
doc     = ["count the number of files of a tar"]
cli     = [{ name="<1>fpath", type="str", default=""}]
actions = [
        {do="job.inject.path.elements", from="{fpath}"},
        {do="tar.list", from="{fpath}", update_="flist"},
        {do="write!", from_="flist", to="{yt_raw}/{fstem}_files_tar.list"}
]
